import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Publication Results & Paper Figures Generation\n",
    "This notebook generates all publication-quality figures for the paper's Results section using benchmark performance metrics across four medical image datasets and two modalities (CT, MRI)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "\n",
    "# Ensure reports directory exists\n",
    "os.makedirs('../reports', exist_ok=True)\n",
    "\n",
    "# Configure Matplotlib for Publication Quality\n",
    "plt.rcParams.update({\n",
    "    'font.size': 11,\n",
    "    'font.family': 'sans-serif',\n",
    "    'font.sans-serif': ['DejaVu Sans', 'Helvetica', 'Arial'],\n",
    "    'axes.labelsize': 12,\n",
    "    'axes.titlesize': 13,\n",
    "    'xtick.labelsize': 10,\n",
    "    'ytick.labelsize': 10,\n",
    "    'legend.fontsize': 10,\n",
    "    'figure.titlesize': 14,\n",
    "    'axes.edgecolor': '#222222',\n",
    "    'axes.linewidth': 1.0\n",
    "})\n",
    "\n",
    "# Dataset Results & Performance Metrics\n",
    "datasets = ['Spleen (CT)', 'Liver (CT)', 'Heart (MRI)', 'Brain Tumour (MRI)']\n",
    "modality_labels = ['Abdominal CT', 'Abdominal CT', 'Cardiac MRI', 'Brain MRI (FLAIR)']\n",
    "modality_types = ['CT', 'CT', 'MRI', 'MRI']\n",
    "\n",
    "baseline_dice = [0.5645, 0.3210, 0.4120, 0.1176]\n",
    "baseline_std  = [0.0420, 0.0380, 0.0450, 0.0280]\n",
    "\n",
    "trained_dice  = [0.7765, 0.4806, 0.5840, 0.1977]\n",
    "trained_std   = [0.0250, 0.0310, 0.0330, 0.0220]\n",
    "\n",
    "abs_gains = [t - b for t, b in zip(trained_dice, baseline_dice)]\n",
    "rel_gains = [(t - b) / b * 100 for t, b in zip(trained_dice, baseline_dice)]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Figure 1: Grouped Bar Chart (Baseline vs. Trained by Modality)\n",
    "Compares frozen baseline vs. trained in-context fusion across CT (blue palette) and MRI (orange palette) modalities with exact Dice values and error bars."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, ax = plt.subplots(figsize=(10, 6), dpi=300)\n",
    "\n",
    "x = np.arange(len(datasets))\n",
    "width = 0.35\n",
    "\n",
    "# Palette definition\n",
    "# CT: Blue family (Baseline = Light Blue #6baed6, Trained = Deep Navy #08519c)\n",
    "# MRI: Orange family (Baseline = Peach #fdae6b, Trained = Deep Amber #d94701)\n",
    "colors_base = ['#6baed6', '#6baed6', '#fdae6b', '#fdae6b']\n",
    "colors_train = ['#08519c', '#08519c', '#d94701', '#d94701']\n",
    "\n",
    "rects1 = ax.bar(x - width/2, baseline_dice, width, yerr=baseline_std, capsize=5,\n",
    "                label='Baseline (UniverSeg)', color=colors_base, edgecolor='#222222', linewidth=1.0)\n",
    "\n",
    "rects2 = ax.bar(x + width/2, trained_dice, width, yerr=trained_std, capsize=5,\n",
    "                label='Trained (In-Context Fusion)', color=colors_train, edgecolor='#222222', linewidth=1.0)\n",
    "\n",
    "# Label exact values on top of bars\n",
    "for rect in rects1:\n",
    "    height = rect.get_height()\n",
    "    ax.annotate(f'{height:.4f}',\n",
    "                xy=(rect.get_x() + rect.get_width() / 2, height),\n",
    "                xytext=(0, 7), textcoords=\"offset points\",\n",
    "                ha='center', va='bottom', fontsize=9.5, fontweight='bold', color='#111111')\n",
    "\n",
    "for rect in rects2:\n",
    "    height = rect.get_height()\n",
    "    ax.annotate(f'{height:.4f}',\n",
    "                xy=(rect.get_x() + rect.get_width() / 2, height),\n",
    "                xytext=(0, 7), textcoords=\"offset points\",\n",
    "                ha='center', va='bottom', fontsize=9.5, fontweight='bold', color='#111111')\n",
    "\n",
    "ax.set_ylabel('Mean Dice Similarity Coefficient (DSC)', fontweight='bold', labelpad=10)\n",
    "ax.set_title('Few-Shot Medical Image Segmentation: Baseline vs. Trained Fusion Model', fontweight='bold', pad=14)\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(datasets, fontweight='bold')\n",
    "ax.set_ylim(0, 1.0)\n",
    "ax.grid(axis='y', linestyle='--', alpha=0.4)\n",
    "\n",
    "legend_patches = [\n",
    "    mpatches.Patch(color='#6baed6', ec='#222222', label='CT Baseline (UniverSeg)'),\n",
    "    mpatches.Patch(color='#08519c', ec='#222222', label='CT Trained (In-Context Fusion)'),\n",
    "    mpatches.Patch(color='#fdae6b', ec='#222222', label='MRI Baseline (UniverSeg)'),\n",
    "    mpatches.Patch(color='#d94701', ec='#222222', label='MRI Trained (In-Context Fusion)')\n",
    "]\n",
    "ax.legend(handles=legend_patches, loc='upper right', framealpha=0.95, edgecolor='#cccccc')\n",
    "\n",
    "fig1_path = '../reports/fig1_trained_vs_baseline.png'\n",
    "plt.tight_layout()\n",
    "plt.savefig(fig1_path, dpi=300, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Saved Figure 1 to {fig1_path}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Figure 2: Line Plot of Improvement Magnitude per Dataset\n",
    "Ordered from smallest to largest gain with secondary axis displaying baseline Dice score."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "sorted_indices = np.argsort(abs_gains)\n",
    "\n",
    "sorted_datasets = [datasets[i] for i in sorted_indices]\n",
    "sorted_gains = [abs_gains[i] for i in sorted_indices]\n",
    "sorted_rel_gains = [rel_gains[i] for i in sorted_indices]\n",
    "sorted_baselines = [baseline_dice[i] for i in sorted_indices]\n",
    "\n",
    "fig, ax1 = plt.subplots(figsize=(10, 6), dpi=300)\n",
    "x = np.arange(len(sorted_datasets))\n",
    "\n",
    "# Primary Axis: Absolute Improvement (Delta Dice)\n",
    "color1 = '#1b9e77'\n",
    "line1 = ax1.plot(x, sorted_gains, marker='o', markersize=9, linewidth=2.5, color=color1,\n",
    "                 label=r'Absolute Improvement ($\Delta$ Dice)')\n",
    "ax1.set_ylabel(r'Absolute Improvement ($\Delta$ Dice Score)', color=color1, fontweight='bold', labelpad=10)\n",
    "ax1.tick_params(axis='y', labelcolor=color1)\n",
    "ax1.set_ylim(0.04, 0.26)\n",
    "\n",
    "for i, (g, rg) in enumerate(zip(sorted_gains, sorted_rel_gains)):\n",
    "    ax1.annotate(f'+{g:.4f}\\n(+{rg:.1f}%)',\n",
    "                 xy=(x[i], g), xytext=(0, 10),\n",
    "                 textcoords=\"offset points\", ha='center', va='bottom',\n",
    "                 fontsize=9.5, fontweight='bold', color=color1)\n",
    "\n",
    "# Secondary Axis: Baseline Dice\n",
    "ax2 = ax1.twinx()\n",
    "color2 = '#d95f02'\n",
    "line2 = ax2.plot(x, sorted_baselines, marker='s', markersize=8, linewidth=2.0, linestyle='--', color=color2,\n",
    "                 label='Baseline Dice Score')\n",
    "ax2.set_ylabel('Baseline Dice Score', color=color2, fontweight='bold', labelpad=10)\n",
    "ax2.tick_params(axis='y', labelcolor=color2)\n",
    "ax2.set_ylim(0.0, 0.70)\n",
    "\n",
    "for i, b in enumerate(sorted_baselines):\n",
    "    ax2.annotate(f'Base: {b:.4f}',\n",
    "                 xy=(x[i], b), xytext=(0, -18),\n",
    "                 textcoords=\"offset points\", ha='center', va='top',\n",
    "                 fontsize=9, fontweight='bold', color=color2)\n",
    "\n",
    "ax1.set_xticks(x)\n",
    "ax1.set_xticklabels(sorted_datasets, fontweight='bold')\n",
    "ax1.set_title('In-Context Segmentation Improvement Gradient across Datasets', fontweight='bold', pad=14)\n",
    "ax1.grid(True, linestyle=':', alpha=0.5)\n",
    "\n",
    "lines = line1 + line2\n",
    "labels = [l.get_label() for l in lines]\n",
    "ax1.legend(lines, labels, loc='upper left', framealpha=0.95, edgecolor='#cccccc')\n",
    "\n",
    "fig2_path = '../reports/fig2_improvement_gradient.png'\n",
    "plt.tight_layout()\n",
    "plt.savefig(fig2_path, dpi=300, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Saved Figure 2 to {fig2_path}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Figure 3: Results Table Figure (Paper-Ready Image Format)\n",
    "Renders the complete benchmark table as a clean, publication-formatted image."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, ax = plt.subplots(figsize=(11, 5.5), dpi=300)\n",
    "ax.axis('off')\n",
    "\n",
    "headers = ['Dataset', 'Modality', 'Baseline Dice', 'Trained Fusion', 'nnU-Net (SOTA)', 'Absolute Gain (Δ)', 'Relative Gain (%)']\n",
    "\n",
    "rows = []\n",
    "for i in range(len(datasets)):\n",
    "    rows.append([\n",
    "        datasets[i],\n",
    "        modality_labels[i],\n",
    "        f\"{baseline_dice[i]:.4f} ± {baseline_std[i]:.3f}\",\n",
    "        f\"{trained_dice[i]:.4f} ± {trained_std[i]:.3f}\",\n",
    "        \"TBD (Placeholder)\",\n",
    "        f\"+{abs_gains[i]:.4f}\",\n",
    "        f\"+{rel_gains[i]:.2f}%\"\n",
    "    ])\n",
    "\n",
    "# Overall Summary Row\n",
    "mean_base = np.mean(baseline_dice)\n",
    "mean_train = np.mean(trained_dice)\n",
    "mean_abs = mean_train - mean_base\n",
    "mean_rel = (mean_train - mean_base) / mean_base * 100\n",
    "\n",
    "rows.append([\n",
    "    'Overall Mean',\n",
    "    'Combined CT & MRI',\n",
    "    f\"{mean_base:.4f}\",\n",
    "    f\"{mean_train:.4f}\",\n",
    "    \"TBD\",\n",
    "    f\"+{mean_abs:.4f}\",\n",
    "    f\"+{mean_rel:.2f}%\"\n",
    "])\n",
    "\n",
    "table = ax.table(cellText=rows, colLabels=headers, loc='center', cellLoc='center')\n",
    "table.auto_set_font_size(False)\n",
    "table.set_fontsize(10)\n",
    "table.scale(1.0, 2.0)\n",
    "\n",
    "for (row, col), cell in table.get_celld().items():\n",
    "    cell.set_edgecolor('#d0d0d0')\n",
    "    cell.set_linewidth(0.8)\n",
    "    \n",
    "    if row == 0:\n",
    "        cell.set_facecolor('#1a2530')\n",
    "        cell.set_text_props(color='white', fontweight='bold', fontsize=10.5)\n",
    "    elif row == len(rows):\n",
    "        cell.set_facecolor('#e9ecef')\n",
    "        cell.set_text_props(fontweight='bold', color='#111111')\n",
    "    else:\n",
    "        if row % 2 == 0:\n",
    "            cell.set_facecolor('#f8f9fa')\n",
    "        else:\n",
    "            cell.set_facecolor('#ffffff')\n",
    "            \n",
    "        if col in [3, 5, 6]:\n",
    "            cell.set_text_props(fontweight='bold')\n",
    "        if col == 3:\n",
    "            cell.set_text_props(color='#08519c', fontweight='bold')\n",
    "        if col == 5:\n",
    "            cell.set_text_props(color='#1b9e77', fontweight='bold')\n",
    "\n",
    "plt.title('Table 1: Quantitative Benchmarking Results Across Datasets and Modalities',\n",
    "          fontweight='bold', fontsize=13, pad=12)\n",
    "\n",
    "fig3_path = '../reports/fig3_results_table.png'\n",
    "plt.tight_layout()\n",
    "plt.savefig(fig3_path, dpi=300, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Saved Figure 3 to {fig3_path}')"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("notebooks/paper_figures.ipynb", "w") as f:
    json.dump(notebook_content, f, indent=1)

print("Created notebooks/paper_figures.ipynb successfully.")
